FROM --platform=linux/amd64 ubuntu:20.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y vim less man
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake pkg-config liblua5.3-dev git libxcb1-dev libyajl-dev libasound-dev libglib2.0-dev libnl-3-dev libnl-genl-3-dev libudev-dev libx11-dev libxcb-ewmh-dev libxcb-icccm4-dev libxcb-util-dev python-docutils

COPY . /repo
WORKDIR /repo/build
RUN cmake ..
RUN make -j8
RUN make install
